### ISSUE TITLE
[Feature: Free Delivery] Scenario 1: สมาชิก VIP ซื้อหนังสือจำนวน 6 เล่มและไม่เสียค่าจัดส่งสินค้า

### ISSUE THREAD

**Issue by zyracuze** [github-sprint3r/grean-press-01#1]
### Scenario 1

สมาชิก VIP ซื้อหนังสือจำนวน 6 เล่ม
ระบบต้องแสดงข้อความว่า "ไม่เสียค่าจัดส่งสินค้า" หลังจากกดปุ่ม Check Out

**Comment by lukyth** [comment]
move to #4

**Comment by zyracuze** [comment]
@lukyth Bug ครับ https://github.com/github-sprint3r/grean-press-01/issues/4
